"""``squadra init`` scaffolding — emit a complete, annotated project skeleton.

One command drops everything a consumer needs to adopt squadra into a target
repo:

- ``squadra.toml`` — a heavily-commented config with **every** key set to its
  built-in default (sourced from :mod:`squadra.config`), so the file documents
  the defaults and the layered precedence at the same time.
- ``runner-skill.md`` / ``cleanup-skill.md`` — consumer-owned skill templates
  (shipped as package data under ``_templates/`` and resolved via
  :mod:`squadra._resources`), with clearly-marked fill-in sections.

The emitted ``squadra.toml`` is round-trip safe: it parses with ``tomllib`` and
loads cleanly through :func:`squadra.config.load_config` (verified in the unit
tests). For the default provider (``ado``) the ``[board.states]`` table is the
inferable To Do/Doing/Done and may be omitted; for any other provider the table
is a REQUIRED placeholder the consumer must edit (their statuses are
user-defined and cannot be inferred).

HANDOFF (Session 2): the unified argparse ``squadra`` CLI must fold this
module's ``init`` subcommand in (see the note near :func:`main`). This module
deliberately does NOT touch ``cli.py``; ``python -m squadra.scaffold init`` is
the standalone entry point until then.
"""

import argparse
from collections.abc import Sequence
import os
from pathlib import Path

from squadra._resources import resolve_template
from squadra.config import (
    CONFIG_FILENAME,
    DEFAULT_BASE_BRANCH,
    DEFAULT_BRANCH_TEMPLATE,
    DEFAULT_CLEANUP_SKILL,
    DEFAULT_PROVIDER,
    DEFAULT_QA_SKILL,
    DEFAULT_RUNNER_SKILL,
    DEFAULT_TDD_SKILL,
    DEFAULT_WORKTREE_DIR,
)
from squadra.constants import DEFAULT_TAG_PREFIX

RUNNER_SKILL_TEMPLATE: str = "runner-skill.md"
CLEANUP_SKILL_TEMPLATE: str = "cleanup-skill.md"

# Where the scaffolded skill templates land in the target repo, by default. Kept
# alongside squadra.toml so a fresh checkout is self-describing.
RUNNER_SKILL_FILENAME: str = "runner-skill.md"
CLEANUP_SKILL_FILENAME: str = "cleanup-skill.md"


def render_squadra_toml(provider: str = DEFAULT_PROVIDER) -> str:
    """Render a complete, annotated ``squadra.toml`` with all defaults inlined.

    Every key carries its built-in default value (the single source of truth is
    :mod:`squadra.config`), so the emitted file doubles as the reference for
    what each knob does and what it defaults to. ``provider`` is written into
    ``[board].provider``.

    For the inferable default provider (``ado``) the ``[board.states]`` table is
    the ADO-Basic To Do/Doing/Done, annotated as omittable. For any other
    provider it is a REQUIRED placeholder the consumer must edit — but it is
    emitted with concrete (placeholder) values so the file still parses and
    loads (load_config requires all three buckets for non-ADO providers).
    """
    states_block: str = _render_states_block(provider)
    return f"""\
# squadra.toml — generated by `squadra init`.
#
# This file documents EVERY configurable knob with its built-in default value.
# Delete or edit whatever you like; deleting a key just falls back to the
# default shown.
#
# Precedence (lowest to highest):
#     built-in defaults  <  squadra.toml  <  FLEET_* env  <  CLI flag
#
# Operational/secret knobs are ENV-ONLY (not in this file): FLEET_MAX_RUNNERS,
# FLEET_HEARTBEAT_INTERVAL_SECONDS, FLEET_STALENESS_THRESHOLD_SECONDS,
# FLEET_MAX_ATTEMPTS, FLEET_MODEL, FLEET_EFFORT, FLEET_HOME, FLEET_ROOT,
# FLEET_PYTHON, and the provider PAT (e.g. AZURE_DEVOPS_EXT_PAT). Set those in
# the environment, not here.

[board]
# Board provider. Defaults to "ado". Override: [board].provider / FLEET_PROVIDER
# / `squadra --provider`.
provider = "{provider}"

# Base branch slices merge into. Override: FLEET_BASE_BRANCH.
base_branch = "{DEFAULT_BASE_BRANCH}"

# Namespace prefix for the fleet's board tags (the five canonical suffixes —
# claimed/failed/needs-decision/qa-ready/awaiting-pr-approval — hang off this).
# Override: FLEET_TAG_PREFIX.
tag_prefix = "{DEFAULT_TAG_PREFIX}"

# Optional parent-link claim filter: only claim work items under these parent
# ids (epics/features). Empty = claim from the whole board. Override:
# FLEET_PARENT_SCOPE_IDS / FLEET_EPIC_IDS (comma-separated).
parent_scope_ids = []

{states_block}
[pipeline]
# Feature-branch name template per slice. `{{id}}` and `{{slug}}` are filled in.
branch_template = "{DEFAULT_BRANCH_TEMPLATE}"

# Where per-slice git worktrees are created (relative to FLEET_HOME).
worktree_dir = "{DEFAULT_WORKTREE_DIR}"

# The consumer-owned skill names the fleet invokes. `squadra init` also drops
# template skill files (runner-skill.md / cleanup-skill.md) you wire in under
# these names. The runner skill receives the tdd/qa skill names as prompt
# arguments and invokes those (it does not hardcode them).
runner_skill = "{DEFAULT_RUNNER_SKILL}"
tdd_skill = "{DEFAULT_TDD_SKILL}"
qa_skill = "{DEFAULT_QA_SKILL}"
cleanup_skill = "{DEFAULT_CLEANUP_SKILL}"
"""


def _render_states_block(provider: str) -> str:
    """Render the ``[board.states]`` table appropriate to ``provider``.

    ADO-Basic's process is inferable, so the table is emitted as optional. Every
    other provider's statuses are user-defined, so the table is REQUIRED and the
    emitted values are placeholders the consumer must replace.
    """
    if provider == DEFAULT_PROVIDER:
        return """\
# [board.states] maps squadra's three neutral lifecycle buckets to your board's
# native state names (lists; many native names may map to one bucket). For the
# "ado" provider this is OPTIONAL — ADO-Basic's To Do/Doing/Done is inferred if
# you omit the table. Shown here (inferred defaults) for reference:
[board.states]
queued = ["To Do"]
active = ["Doing"]
done = ["Done"]
"""
    return f"""\
# [board.states] is REQUIRED for provider "{provider}": its statuses are
# user-defined and cannot be inferred. EDIT the values below to your board's
# actual native state names (lists; many native names may map to one bucket).
[board.states]
queued = ["TODO"]        # <-- EDIT: your "not started" state name(s)
active = ["In Progress"] # <-- EDIT: your "in flight" state name(s)
done = ["Done"]          # <-- EDIT: your "finished" state name(s)
"""


def _write_file(path: Path, content: str, *, force: bool) -> bool:
    """Write ``content`` to ``path``. Returns ``True`` if written, ``False`` if skipped.

    Refuses to clobber an existing file unless ``force`` is set, in which case it
    overwrites. A pre-existing file without ``force`` is reported as skipped
    (``False``), not an error, so a partial init can simply be re-run.
    """
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def init_project(
    target_dir: Path,
    *,
    provider: str = DEFAULT_PROVIDER,
    force: bool = False,
) -> dict[str, bool]:
    """Scaffold ``squadra.toml`` + the two skill templates into ``target_dir``.

    Reads the skill templates from package data via
    :func:`squadra._resources.resolve_template`. Returns a mapping of the
    written filename to whether it was written (``True``) or skipped because it
    already existed and ``force`` was not set (``False``).
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    runner_tpl: str = resolve_template(RUNNER_SKILL_TEMPLATE).read_text(encoding="utf-8")
    cleanup_tpl: str = resolve_template(CLEANUP_SKILL_TEMPLATE).read_text(encoding="utf-8")

    artifacts: dict[str, str] = {
        CONFIG_FILENAME: render_squadra_toml(provider),
        RUNNER_SKILL_FILENAME: runner_tpl,
        CLEANUP_SKILL_FILENAME: cleanup_tpl,
    }
    return {
        name: _write_file(target_dir / name, content, force=force)
        for name, content in artifacts.items()
    }


def _resolve_target_dir(raw: str | None) -> Path:
    """Resolve the scaffold target directory (``--dir`` flag, FLEET_HOME, or cwd)."""
    if raw is not None and raw.strip():
        return Path(raw)
    env: str | None = os.environ.get("FLEET_HOME")
    if env is not None and env.strip():
        return Path(env)
    return Path.cwd()


def main(argv: Sequence[str] | None = None) -> int:
    """Run the standalone ``squadra.scaffold`` CLI (the ``init`` subcommand).

    The unified ``squadra init`` (in :mod:`squadra.cli`) is the primary entry
    point; this stays the direct module entry point
    (``python -m squadra.scaffold init ...``) for the same scaffolding.
    """
    parser = argparse.ArgumentParser(
        prog="squadra.scaffold",
        description="Scaffold a squadra.toml + consumer-owned skill templates.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    init_parser = subparsers.add_parser(
        "init", help="write squadra.toml + runner/cleanup skill templates"
    )
    init_parser.add_argument(
        "--provider",
        default=DEFAULT_PROVIDER,
        help=f"board provider written into [board].provider (default: {DEFAULT_PROVIDER})",
    )
    init_parser.add_argument(
        "--dir",
        dest="target_dir",
        default=None,
        help="target directory (default: $FLEET_HOME, else the current directory)",
    )
    init_parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing files instead of skipping them",
    )
    args = parser.parse_args(argv)

    target: Path = _resolve_target_dir(args.target_dir)
    results: dict[str, bool] = init_project(target, provider=args.provider, force=args.force)
    for name, written in results.items():
        status: str = "wrote" if written else "skipped (exists; use --force)"
        print(f"{status}: {target / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
